# Generated by Django 5.1.5 on 2025-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('TECH', 'IT技術'), ('MARKETING', 'マーケティング'), ('DESIGN', 'デザイン'), ('BLOG', 'ブログ'), ('PSYCHOLOGY', '心理学'), ('BEHAVIORAL_ECONOMICS', '行動経済学'), ('BRAIN_SCIENCE', '脳科学'), ('HUMAN_BODY', '人体'), ('OTHER', 'その他')], default='TECH', max_length=200, verbose_name='カテゴリ'),
        ),
    ]
