# Generated by Django 5.1.5 on 2025-03-17 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_header_img_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='uploadedfileurl',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='header_img_url',
            field=models.FileField(blank=True, upload_to='header_img/', verbose_name='ヘッダー画像格納先'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='favorite_unique'),
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
        migrations.DeleteModel(
            name='UploadedFileUrl',
        ),
    ]
