# Generated by Django 5.1.5 on 2025-03-17 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_articletag_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('article_category_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='記事カテゴリID')),
                ('name', models.CharField(max_length=200, verbose_name='記事カテゴリ名')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '記事カテゴリマスタ',
                'verbose_name_plural': '記事カテゴリマスタ',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.articlecategory'),
        ),
    ]
