# Generated by Django 5.1.5 on 2025-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articlecategory_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='記事ID'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='article_category_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='記事カテゴリID'),
        ),
    ]
