# Generated by Django 5.1.5 on 2025-03-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedCount',
            fields=[
                ('count_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='カウントID')),
                ('viewed_count', models.IntegerField(default=0, verbose_name='ビュー回数')),
            ],
            options={
                'verbose_name': '記事閲覧回数マスタ',
                'verbose_name_plural': '記事閲覧回数マスタ',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='viewed_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.viewedcount'),
        ),
    ]
