# Generated by Django 5.1.5 on 2025-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_viewedcount_alter_article_viewed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='お気に入り登録日'),
        ),
    ]
