# Generated by Django 5.1.5 on 2025-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='プロダクトID')),
                ('name', models.CharField(max_length=150, verbose_name='プロダクト名')),
                ('content', models.TextField(verbose_name='コンテンツ')),
                ('header_img_url', models.ImageField(upload_to='', verbose_name='ヘッダー画像格納先')),
                ('reated_at', models.DateField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': 'プロダクトマスタ',
                'verbose_name_plural': 'プロダクトマスタ',
            },
        ),
    ]
