# Generated by Django 5.1.5 on 2025-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='access_url',
            field=models.CharField(default=1, max_length=150, verbose_name='プロダクト名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='header_img_url',
            field=models.ImageField(upload_to='product_images/', verbose_name='ヘッダー画像格納先'),
        ),
    ]
