# Generated by Django 5.1.5 on 2025-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='access_url',
            field=models.CharField(max_length=150, verbose_name='リンク先'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='プロダクトID'),
        ),
    ]
