# Generated by Django 5.1.5 on 2025-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最終ログイン'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
