# Generated by Django 5.1.5 on 2025-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_serviceuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID'),
        ),
    ]
