# Generated by Django 5.1.5 on 2025-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilities',
            name='capability_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='資格ID'),
        ),
        migrations.AlterField(
            model_name='interesteddomain',
            name='domain_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ドメインID'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='carrer_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='プロダクトID'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content2',
            field=models.TextField(null=True, verbose_name='キャリア内容2'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content3',
            field=models.TextField(null=True, verbose_name='キャリア内容3'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content4',
            field=models.TextField(null=True, verbose_name='キャリア内容4'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content5',
            field=models.TextField(null=True, verbose_name='キャリア内容5'),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='category',
            field=models.TextField(choices=[('FRONTEND', 'フロントエンド'), ('BACKEND', 'バックエンド'), ('OS/DB', 'OS・DB'), ('INFRASTRUCTURE', 'インフラ'), ('OTHER', 'その他')], verbose_name='スキルカテゴリ'),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='skill_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='プロダクトID'),
        ),
    ]
