# Generated by Django 5.1.5 on 2025-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_capabilities_capability_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycareer',
            name='career_ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='キャリア終了日'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='キャリア内容2'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content3',
            field=models.TextField(blank=True, null=True, verbose_name='キャリア内容3'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content4',
            field=models.TextField(blank=True, null=True, verbose_name='キャリア内容4'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='content5',
            field=models.TextField(blank=True, null=True, verbose_name='キャリア内容5'),
        ),
    ]
