# Generated by Django 5.1.5 on 2025-03-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_mycareer_career_ended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('skill_category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='スキルカテゴリ名')),
                ('name', models.CharField(max_length=150, verbose_name='スキルカテゴリ名')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'スキルカテゴリ',
                'verbose_name_plural': 'スキルカテゴリ',
            },
        ),
        migrations.AlterField(
            model_name='myskill',
            name='skill_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='スキルID'),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='about.skillcategory'),
        ),
    ]
