# Generated by Django 5.1.5 on 2025-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_skillcategory_alter_myskill_skill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='interesteddomain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='career_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='キャリア終了日'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='career_started_at',
            field=models.DateTimeField(verbose_name='キャリア開始日'),
        ),
        migrations.AlterField(
            model_name='mycareer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
