# Generated by Django 5.1.5 on 2025-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_capabilities_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('release_note_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='リリースノートID')),
                ('version', models.CharField(max_length=150, verbose_name='バージョン')),
                ('content', models.TextField(verbose_name='アップデート内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'リリースノートマスタ',
                'verbose_name_plural': 'リリースノートマスタ',
            },
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'スキルカテゴリマスタ', 'verbose_name_plural': 'スキルカテゴリマスタ'},
        ),
    ]
