# Generated by Django 5.1.5 on 2025-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_releasenote_alter_skillcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenote',
            name='content',
        ),
        migrations.AddField(
            model_name='releasenote',
            name='bug_fix',
            field=models.TextField(blank=True, null=True, verbose_name='バグ修正'),
        ),
        migrations.AddField(
            model_name='releasenote',
            name='improvement',
            field=models.TextField(blank=True, null=True, verbose_name='改善'),
        ),
        migrations.AddField(
            model_name='releasenote',
            name='new_feature',
            field=models.TextField(blank=True, null=True, verbose_name='新機能'),
        ),
        migrations.AddField(
            model_name='releasenote',
            name='overview',
            field=models.TextField(default='', verbose_name='概要'),
            preserve_default=False,
        ),
    ]
