# Generated by Django 5.1.5 on 2025-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_releasenote_content_releasenote_bug_fix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenote',
            name='bug_fix',
        ),
        migrations.RemoveField(
            model_name='releasenote',
            name='overview',
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='improvement',
            field=models.TextField(blank=True, null=True, verbose_name='改善・バグ修正'),
        ),
    ]
