# Generated by Django 5.1.5 on 2025-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_releasenote_bug_fix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='skill_icon',
            field=models.ImageField(default='', upload_to='skill_icon/', verbose_name='スキルアイコン'),
            preserve_default=False,
        ),
    ]
