# Generated by Django 5.1.5 on 2025-03-22 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_myskill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilities',
            name='got_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='取得日'),
            preserve_default=False,
        ),
    ]
